// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oid85.FinMarket.DataAccess;

#nullable disable

namespace Oid85.FinMarket.DataAccess.Migrations
{
    [DbContext(typeof(FinMarketContext))]
    partial class FinMarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.AnalyseResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("analyse_result_type_id");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<Guid>("TimeframeId")
                        .HasColumnType("uuid")
                        .HasColumnName("timeframe_id");

                    b.HasKey("Id")
                        .HasName("pk_analyse_results");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("ix_analyse_results_ticker");

                    b.HasIndex("TimeframeId")
                        .HasDatabaseName("ix_analyse_results_timeframe_id");

                    b.ToTable("analyse_results", "storage");
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.BondEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Figi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("figi");

                    b.Property<bool>("InPortfolio")
                        .HasColumnType("boolean")
                        .HasColumnName("in_portfolio");

                    b.Property<bool>("InWatchList")
                        .HasColumnType("boolean")
                        .HasColumnName("in_watch_list");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isin");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bonds");

                    b.ToTable("bonds", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.CandleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<Guid>("TimeframeId")
                        .HasColumnType("uuid")
                        .HasColumnName("timeframe_id");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_candles");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("ix_candles_ticker");

                    b.HasIndex("TimeframeId")
                        .HasDatabaseName("ix_candles_timeframe_id");

                    b.ToTable("candles", "storage");
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.DividendInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeclaredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declared_date");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<double>("Dividend")
                        .HasColumnType("double precision")
                        .HasColumnName("dividend");

                    b.Property<double>("DividendPrc")
                        .HasColumnType("double precision")
                        .HasColumnName("dividend_prc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dividend_info_entities");

                    b.HasIndex("ShareId")
                        .HasDatabaseName("ix_dividend_info_entities_share_id");

                    b.ToTable("dividend_info_entities", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.ShareEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Figi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("figi");

                    b.Property<bool>("InIrusIndex")
                        .HasColumnType("boolean")
                        .HasColumnName("in_irus_index");

                    b.Property<bool>("InPortfolio")
                        .HasColumnType("boolean")
                        .HasColumnName("in_portfolio");

                    b.Property<bool>("InWatchList")
                        .HasColumnType("boolean")
                        .HasColumnName("in_watch_list");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isin");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shares");

                    b.ToTable("shares", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.TimeframeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_timeframes");

                    b.ToTable("timeframes", "dict");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaa80987-548b-474d-8882-9003a10db167"),
                            CreatedAt = new DateTime(2024, 10, 27, 18, 51, 53, 582, DateTimeKind.Utc).AddTicks(9858),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1 день",
                            IsDeleted = false,
                            Name = "D",
                            UpdatedAt = new DateTime(2024, 10, 27, 18, 51, 53, 582, DateTimeKind.Utc).AddTicks(9861)
                        },
                        new
                        {
                            Id = new Guid("827adf38-2f99-4066-ba5c-33a646d2767b"),
                            CreatedAt = new DateTime(2024, 10, 27, 18, 51, 53, 582, DateTimeKind.Utc).AddTicks(9926),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1 час",
                            IsDeleted = false,
                            Name = "H",
                            UpdatedAt = new DateTime(2024, 10, 27, 18, 51, 53, 582, DateTimeKind.Utc).AddTicks(9927)
                        });
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.AnalyseResultEntity", b =>
                {
                    b.HasOne("Oid85.FinMarket.DataAccess.Entities.TimeframeEntity", "Timeframe")
                        .WithMany()
                        .HasForeignKey("TimeframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analyse_results_timeframe_entities_timeframe_id");

                    b.Navigation("Timeframe");
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.CandleEntity", b =>
                {
                    b.HasOne("Oid85.FinMarket.DataAccess.Entities.TimeframeEntity", "Timeframe")
                        .WithMany()
                        .HasForeignKey("TimeframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candles_timeframe_entities_timeframe_id");

                    b.Navigation("Timeframe");
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.DividendInfoEntity", b =>
                {
                    b.HasOne("Oid85.FinMarket.DataAccess.Entities.ShareEntity", "Share")
                        .WithMany("DividendInfoEntities")
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_dividend_info_entities_share_entities_share_id");

                    b.Navigation("Share");
                });

            modelBuilder.Entity("Oid85.FinMarket.DataAccess.Entities.ShareEntity", b =>
                {
                    b.Navigation("DividendInfoEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
