// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oid85.FinMarket.DAL;

#nullable disable

namespace Oid85.FinMarket.DAL.Migrations
{
    [DbContext(typeof(StorageDataBaseContext))]
    partial class StorageDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oid85.FinMarket.DAL.Entities.AssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Figi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("figi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.ToTable("assets", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da48943a-eed9-42ce-b0d6-c7a6ccdf3fc2"),
                            Figi = "BBG002W2FT78",
                            Name = "Абрау-Дюрсо, акция обыкновенная",
                            Sector = "Агропром и Пищепром",
                            Ticker = "ABRD"
                        },
                        new
                        {
                            Id = new Guid("84072df0-85d8-4135-be2d-f508cd5c01eb"),
                            Figi = "BBG004S683X6",
                            Name = "Аэрофлот, акция обыкновенная",
                            Sector = "Транспорт",
                            Ticker = "AFLT"
                        },
                        new
                        {
                            Id = new Guid("007dad9d-9dd6-4f5c-8cba-ee634db20be4"),
                            Figi = "BBG004S688H3",
                            Name = "Акрон, акция обыкновенная",
                            Sector = "Химия, удобрения",
                            Ticker = "AKRN"
                        },
                        new
                        {
                            Id = new Guid("a4df3b20-a222-43cf-851e-bd3b705c0bd4"),
                            Figi = "BBG004S68B40",
                            Name = "Алроса, акция обыкновенная",
                            Sector = "Горнодобывающие",
                            Ticker = "ALRS"
                        },
                        new
                        {
                            Id = new Guid("bf5d3d04-bfaa-4623-9a65-7431d00b2a86"),
                            Figi = "BBG004730N97",
                            Name = "Сбербанк, акция обыкновенная",
                            Sector = "Банки",
                            Ticker = "SBER"
                        });
                });

            modelBuilder.Entity("Oid85.FinMarket.DAL.Entities._1D_CandleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("_1D", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.DAL.Entities._1H_CandleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("_1H", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.DAL.Entities._1M_CandleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("_1M", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
